<%@ Page Title="Admin Teams" Language="C#" MasterPageFile="~/Site.Master" Async="True" EnableViewState="True"
    AutoEventWireup="true" CodeBehind="AdminTeams.aspx.cs" Inherits="GamePoolWeb2.AdminTeams" MaintainScrollPositionOnPostback="true" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>.</h2>
    <h3>

    </h3>
    <asp:Button runat="server" Text="Add Team" OnClick="AddTeam_Click" />
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowEditing="GridView1_RowEditing" 
        OnRowUpdating="GridView1_RowUpdating" OnRowCancelingEdit="GridView1_RowCancelling" OnRowDeleting="GridView1_RowDeleting">
        <AlternatingRowStyle BackColor="LightBlue"></AlternatingRowStyle>
        <Columns>            
            <asp:BoundField ReadOnly="true" DataField="Id" HeaderText="Id"/>
            <asp:BoundField DataField="Description" HeaderText="Team Name"/>
        </Columns>
    </asp:GridView>
                
</asp:Content>
