<%@ Page Title="Admin Games" Language="C#" MasterPageFile="~/Site.Master" Async="True" EnableViewState="True"
    AutoEventWireup="true" CodeBehind="AdminGames.aspx.cs" Inherits="GamePoolWeb2.AdminGames" MaintainScrollPositionOnPostback="true" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>.</h2>
    <h3>

    </h3>
    <asp:Button runat="server" Text="Calculate User Standings" OnClick="CalculateScores_Click" />
    <br/>
    <asp:Button runat="server" Text="Lock Games" OnClick="LockGames_Click" />
    <asp:Button runat="server" Text="Unlock Games" OnClick="UnlockGames_Click" />
    <br/>
    <asp:Button runat="server" Text="Add Game" OnClick="AddGame_Click" />
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        OnRowEditing="GridView1_RowEditing" 
        OnRowUpdating="GridView1_RowUpdating" OnRowCancelingEdit="GridView1_RowCancelling" OnRowDeleting="GridView1_RowDeleting"
        OnRowDataBound="GridView1_RowDataBound">
        <AlternatingRowStyle BackColor="LightBlue"></AlternatingRowStyle>
        <Columns>            
            <%--<asp:BoundField ReadOnly="true" DataField="Id" HeaderText="Id"/>--%>
            <asp:TemplateField HeaderText="Id">
              <EditItemTemplate>
                <asp:Label runat="server" Text='<%# Eval("Id") %>' Font-Size="1"></asp:Label>
              </EditItemTemplate> 
                <ItemTemplate>
                    <asp:Label runat="server" Text='<%# Eval("Id") %>'  Font-Size="1"></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>

            <asp:BoundField DataField="Description" HeaderText="Team Name"/>
            
            <asp:TemplateField HeaderText="Home Team">
              <EditItemTemplate>
                <asp:DropDownList runat="server" ID="HomeTeams" DataTextField="Description" DataValueField="Id"  DataSource='<%# GetTeams %>' />
              </EditItemTemplate> 
                <ItemTemplate>
                    <asp:Label runat="server" Text='<%# GetTeamDescription(Eval("HomeTeamId")) %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Away Team">
              <EditItemTemplate>
                <asp:DropDownList runat="server" ID="AwayTeams" DataTextField="Description" DataValueField="Id"  DataSource='<%# GetTeams %>'  />  
              </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label runat="server" Text='<%# GetTeamDescription(Eval("AwayTeamId")) %>'></asp:Label>
              </ItemTemplate> 
            </asp:TemplateField>

            <asp:BoundField DataField="Network" HeaderText="Network"/>
            <asp:BoundField DataField="GameDateTime" HeaderText="Time"/>
            <asp:BoundField DataField="HomeScore" HeaderText="Home Score"/>
            <asp:BoundField DataField="AwayScore" HeaderText="Away Score"/>
            <asp:BoundField DataField="IsGameFinished" HeaderText="Finished"/>
        </Columns>
    </asp:GridView>
                
</asp:Content>
